version: '3.9'
services:

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NPM_GITHUB_TOKEN=${NPM_GITHUB_TOKEN}
    container_name: nodejs
    restart: unless-stopped
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:80
    command: npm run start
