export enum FileTemplateErrorCode {
  E404_FILE_TEMPLATE = 'E404_FILE_TEMPLATE',
}

export enum FileErrorCode {
  E404_FILE = 'E404_FILE',
  E404_FILE_MIME_TYPE = 'E404_FILE_MIME_TYPE',
  E409_FILE_SIZE_EXCEEDED = 'E409_FILE_SIZE_EXCEEDED',
  E409_FILE_DUPLICATE_REFERENCE_NUMBER = 'E409_FILE_DUPLICATE_REFERENCE_NUMBER',
  E409_FILE_ARCHIVE_STATE_NOT_ALLOWED = 'E409_FILE_ARCHIVE_STATE_NOT_ALLOWED',
  E409_FILE_ARCHIVE_ALREADY_ARCHIVED = 'E409_FILE_ARCHIVE_ALREADY_ARCHIVED',
}

export enum PluginErrorCode {
  E404_PLUGIN = 'E404_PLUGIN',
  E409_PLUGIN_ALREADY_REGISTERED = 'E409_PLUGIN_ALREADY_REGISTERED',
  E400_PLUGIN_INVALID_WEBHOOK_URL = 'E400_PLUGIN_INVALID_WEBHOOK_URL',
}
